---
name: check case insensitivity

# yamllint disable-line rule:truthy
on:
  pull_request:
  push:

jobs:
  run-python-platform:
    name: os:${{ matrix.os }} / version:${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
        python-version:
          - 3.12
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: call code
        run: |
          python check_uniqueness.py
      - name: install IPython
        run: |
          python -m pip install ipython
      - name: time code
        run: |
          ipython time_uniqueness.ipy
